server:
  port:
    8081
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: data-microservice
          uri: lb://data-microservice
          predicates:
            - Path=/data/*
        - id: justificativo-microservice
          uri: lb://justificativo-microservice
          predicates:
            - Path=/justificativo/*
        - id: autorizacion-microservice
          uri: lb://autorizacion-microservice
          predicates:
            - Path=/autorizacion/*
        - id: sueldo-microservice
          uri: lb://sueldo-microservice
          predicates:
            - Path=/sueldo/*
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}